plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	flatDir { dirs 'libs' }
	maven {
		name = "BlameJared"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "GeckoLib"
		url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
	}
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/releases/"
	}
	maven {
		name = "Ladysnake Mods"
		url = "https://maven.ladysnake.org/releases"
	}
}

loom {
	splitEnvironmentSourceSets()

	mixin {
		useLegacyMixinAp = true
		defaultRefmapName = "ssc_furniture-refmap.json"
	}

	mods {
		"ssc_furniture" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modCompileOnly "net.onixary:shape-shifter-curse-fabric:1.10.0"
	modCompileOnly("software.bernie.geckolib:geckolib-fabric-1.20.1:${geckolib_version}") { transitive = false }
	modLocalRuntime("software.bernie.geckolib:geckolib-fabric-1.20.1:${geckolib_version}") { transitive = false }
	modCompileOnly("com.terraformersmc:modmenu:7.2.2") { transitive = false }
	modLocalRuntime("com.terraformersmc:modmenu:7.2.2") { transitive = false }
	modLocalRuntime "mezz.jei:jei-1.20.1-fabric:${project.jei_version}"
	modCompileOnly "dev.emi:trinkets:3.7.2"
	modCompileOnly("io.github.apace100:apoli:2.9.2+mc.1.20.x") { transitive = false }
	modCompileOnly("io.github.apace100:calio:1.11.2+mc.1.20.x") { transitive = false }
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
